name: Reusable Docker Build and Push Workflow

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      dockerfile:
        required: true
        type: string
      docker_repo:
        required: true
        type: string
      build_args:
        required: false
        type: string
        default: "{}"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Parse build arguments
        id: args
        run: echo '${{ inputs.build_args }}' | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' > $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ inputs.docker_repo }}:latest
          build-args: ${{ steps.args.outputs.args }}
